--RAPPORT

--1 
SELECT UTILISATEUR.NOM, UTILISATEUR.IDUTILISATEUR
FROM UTILISATEUR
JOIN PASSAGER
ON PASSAGER.UTILISATEUR_IDUTILISATEUR = UTILISATEUR.IDUTILISATEUR
JOIN BILLET
ON BILLET.PASSAGER_IDPASSAGER = PASSAGER.IDPASSAGER
JOIN VOL
ON BILLET.VOL_NUMEROVOL = VOL.NUMEROVOL
JOIN TRANSPORTEUR
ON VOL.TRANSPORTEUR_IDTRANSPORTEUR = TRANSPORTEUR.IDTRANSPORTEUR
ORDER by BILLET.PRIX
fetch first 3 rows only;

--2
SELECT UTILISATEUR.NOM, PASSAGER.IDPASSAGER
FROM PASSAGER
JOIN BILLET
ON BILLET.PASSAGER_IDPASSAGER = PASSAGER.IDPASSAGER
JOIN UTILISATEUR
ON UTILISATEUR.IDUTILISATEUR = PASSAGER.UTILISATEUR_IDUTILISATEUR
ORDER by BILLET.PRIX;

--3
SELECT AEROPORT.NOM, BILLET.PRIX
FROM AEROPORT
JOIN VOL_AEROPORT
ON AEROPORT.IDAEROPORT = VOL_AEROPORT.AEROPORT_IDAEROPORT
JOIN VOL
ON VOL.NUMEROVOL = VOL_AEROPORT.VOL_NUMEROVOL
JOIN BILLET
ON VOL.NUMEROVOL = BILLET.VOL_NUMEROVOL
ORDER by BILLET.PRIX;


